# adventofcode

## Day 03


--------
| Author | Andrew Wade |
| :---- | ------|
| Date | xx Oct 2021 | 
| Contact | awade (at) andrew.wade@anu.edu.au|
| Ref | [Day 03](https://adventofcode.com/2020/day/3) |

--- Day 3: Toboggan Trajectory ---

With the toboggan login problems resolved, you set off toward the airport. While travel by toboggan might be easy, it's certainly not safe: there's very minimal steering and the area is covered in trees. You'll need to see which angles will take you near the fewest trees.

Due to the local geology, trees in this area only grow on exact integer coordinates in a grid. You make a map (your puzzle input) of the open squares (.) and trees (#) you can see. For example:

..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
These aren't the only trees, though; due to something you read about once involving arboreal genetics and biome stability, the same pattern repeats to the right many times:

..##.........##.........##.........##.........##.........##.......  --->
#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....#..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..#...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.##.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........#.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...##....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#  --->
You start on the open square (.) in the top-left corner and need to reach the bottom (below the bottom-most row on your map).

The toboggan can only follow a few specific slopes (you opted for a cheaper model that prefers rational numbers); start by counting all the trees you would encounter for the slope right 3, down 1:

From your starting position at the top-left, check the position that is right 3 and down 1. Then, check the position that is right 3 and down 1 from there, and so on until you go past the bottom of the map.

The locations you'd check in the above example are marked here with O where there was an open square and X where there was a tree:

..##.........##.........##.........##.........##.........##.......  --->
#..O#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....X..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#O#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..X...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.X#.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#.O..#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........X.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.X#...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...#X....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...X.#.#..#...#.#.#..#...#.#.#..#...#.#  --->
In this example, traversing the map using this slope would cause you to encounter 7 trees.

Starting at the top-left corner of your map and following a slope of right 3 and down 1, how many trees would you encounter?

Your puzzle answer was 265.

--- Part Two ---

Time to check the rest of the slopes - you need to minimize the probability of a sudden arboreal stop, after all.

Determine the number of trees you would encounter if, for each of the following slopes, you start at the top-left corner and traverse the map all the way to the bottom:

Right 1, down 1.
Right 3, down 1. (This is the slope you already checked.)
Right 5, down 1.
Right 7, down 1.
Right 1, down 2.
In the above example, these slopes would find 2, 7, 3, 4, and 2 tree(s) respectively; multiplied together, these produce the answer 336.

What do you get if you multiply together the number of trees encountered on each of the listed slopes?

In [1]:
#Arrays, Plotting, system
import numpy as np

## Example data

In [10]:
exampleSeedArray = [
    '..##.......',
    '#...#...#..',
    '.#....#..#.',
    '..#.#...#.#',
    '.#...##..#.',
    '..#.##.....',
    '.#.#.#....#',
    '.#........#',
    '#.##...#...',
    '#...##....#',
    '.#..#...#.#']
paternRepeated = 6

# Initiate array
exampleTreeMap = np.zeros((len(exampleSeedArray),paternRepeated*len(exampleSeedArray[1])), dtype=bool)
# Loop to make array of T/F from text with prescribed repeates
for ii, val in enumerate(exampleSeedArray):
    # Probably not optimal convertion to type bool array
    buff = list(val.replace('#', '1').replace('.', '0'))
    buff = [bool(int(numeric_string)) for numeric_string in buff]
    exampleTreeMap[ii] = buff * int(paternRepeated)

In [11]:
slopeDef = (1,3) # (stepsDown, stepsRight)
(N, M) = np.shape(exampleTreeMap)

ii = 0; jj = 0; step = 0;

# Compute the route and presents of trees according to tree map
routeList = {}
while (ii<N) and (jj<M):
    routeList[step] = {}
    routeList[step]['ii'] = ii
    routeList[step]['jj'] = jj
    routeList[step]['tree'] = exampleTreeMap[ii, jj]
    jj = jj + slopeDef[1]
    ii = ii + slopeDef[0]
    step = step + 1
   
countTrees = 0
for val in routeList.values():
    if val['tree']:
        countTrees = countTrees + 1
        
print('Total trees on route = {}.'.format(countTrees))

Total trees on route = 7.


In [12]:
## Import data and compute trees on all the slopes

Import the puzzle input

In [13]:
fileName = 'puzzleInput.txt'

# Import the data into fields
puzzleInput = np.empty((0,1), str)
with open(fileName) as f:
    for line in f:
        puzzleInput = np.vstack((puzzleInput, line.split()))

In [14]:
TreeMap = np.zeros((len(puzzleInput),len(puzzleInput[0][0])), dtype=bool)
# Loop to make array of T/F from text with prescribed repeates
for ii, val in enumerate(puzzleInput):
    # Probably not optimal convertion to type bool array
    buff = list(val[0].replace('#', '1').replace('.', '0'))
    TreeMap[ii] = [bool(int(numeric_string)) for numeric_string in buff]

In [15]:
np.shape(TreeMap)

(323, 31)

## Part 1: Count the trees on a one step down two steps right path
Make a general purose route list generator method and count trees along generated route

In [19]:
slopeDef = (1,1) # (stepsDown, stepsRight)
def findRouteList(TreeMap, slopeDef):
    (N, M) = np.shape(TreeMap)

    ii = 0; jj = 0; step = 0;

    # Compute the route and presents of trees according to tree map
    routeList = {}
    while (ii<N):
        routeList[step] = {}
        routeList[step]['ii'] = ii
        routeList[step]['jj'] = jj
        routeList[step]['tree'] = TreeMap[ii, jj]
        jj = jj + slopeDef[1]
        ii = ii + slopeDef[0]
        jj = jj%M  # Modulo wrap around to fit the pattern in the LR direction
        step = step + 1
    
    return routeList



Now compute the number of trees for special case

In [18]:
routeList = findRouteList(TreeMap, slopeDef)

countTrees = 0
for val in routeList.values():
    if val['tree']:
        countTrees = countTrees + 1
        
print('Total trees on route = {}.'.format(countTrees))

Total trees on route = 61.


## Part 2: Find trees on any arbitrary slope

First define all the requested slopes

In [20]:
slopeLists = np.array([[1,1],
                       [1,3],
                       [1,5],
                       [1,7],
                       [2,1]])

In [21]:
treesList = []
for ii in range(len(slopeLists)):
    routeList = findRouteList(TreeMap, slopeLists[ii])
    
    countTrees = 0
    for val in routeList.values():
        if val['tree']:
            countTrees = countTrees + 1
    
    treesList.append(countTrees)
    print('Total trees on route slope {} = {}.'.format(slopeLists[ii], countTrees))

treesListProduct = 1
for ii in range(len(slopeLists)):
    treesListProduct = treesListProduct*treesList[ii]
print('Product of trees on each of the listed slopes = {}.'.format(treesListProduct))

Total trees on route slope [1 1] = 61.
Total trees on route slope [1 3] = 265.
Total trees on route slope [1 5] = 82.
Total trees on route slope [1 7] = 70.
Total trees on route slope [2 1] = 34.
Product of trees on each of the listed slopes = 3154761400.


## Bonus: Find path out of all the options that gives the least trees

In [37]:
maxStepsDown = 5
maxStepsRight = 5

x = np.arange(0,5)
y = np.arange(0,5)

X, Y = np.meshgrid(x,y)

print(x)

# slopeLists = 1

[0 1 2 3 4]


In [49]:
(np.hstack((np.reshape(X,(-1,1)), np.reshape(Y,(-1,1)))))

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4]])

In [32]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [22]:
treesList = []
for ii in range(len(slopeLists)):
    routeList = findRouteList(TreeMap, slopeLists[ii])
    
    countTrees = 0
    for val in routeList.values():
        if val['tree']:
            countTrees = countTrees + 1
    
    treesList.append(countTrees)
    print('Total trees on route slope {} = {}.'.format(slopeLists[ii], countTrees))

treesListProduct = 1
for ii in range(len(slopeLists)):
    treesListProduct = treesListProduct*treesList[ii]
print('Product of trees on each of the listed slopes = {}.'.format(treesListProduct))

Total trees on route slope [1 1] = 61.
Total trees on route slope [1 3] = 265.
Total trees on route slope [1 5] = 82.
Total trees on route slope [1 7] = 70.
Total trees on route slope [2 1] = 34.
Product of trees on each of the listed slopes = 3154761400.
